
services:
  db:
    image: postgres:17
    container_name: notes_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile   # hier liegt Ihr FastAPI-Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://user:password@db:5432/notes"
    volumes:
      - ./app:/code/app

volumes:
  postgres_data:
